# EN PYTHON LA FUNCION LEN NOS PERMITE OBTENER LA LONGITUD DE UNA CADENA DE CARACTERES
# O BIEN SEA EL NUMERO DE ELEMENTOS QUE OCMPONEN A UN OBJETO

# AHORA VEAMOS UN EJEMPLO

nombre = 'Euclides'
print(f'El nombre {nombre} tiene  {len(nombre)} caracteres')


# CUANDO QUEREMOS SABER CUAL ES LA LONGITUD DE UNA CADENA LOS ESPACIOS TAMBIEN CONTARAN PARA ESO