# EN PYTHON EL SICLO O BUCLE FOR ES UNA ESTRUCTURA REPETITIVA QUE NOS PERMOTE EJECUTAR UN BLOQUE DE INSTRUCCIONES
# SIERTA CANTIDAD DE VECES 

# SINTAXSIS

# for variable in objeto_iterable:
    
# UN OBJETO ITERABLE ES AQUEL QUE PERMOTE RECORRER SUS ELEMENTOS 1 A 1 COMO UNA CADENA DE CARACTERES
# UNA LISTA O UN DICCIONARIO O ARCHIVO
# VEAMOS UN EJEMPLI ITERANDO UNA CADENA DE TEXTO E IMPRIMIENDO SU CONTENIDO

string = 'Hola Mundo'

for letra in string:
    print(letra)
print('Fin')

